# Generated by Django 2.0 on 2017-12-17 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtifactContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('email', models.EmailField(max_length=250, verbose_name='Email')),
                ('phone', models.CharField(max_length=250, verbose_name='Phone')),
                ('artifact_info', models.TextField(blank=True, null=True, verbose_name='Artifact info')),
                ('intend_type', models.PositiveSmallIntegerField(choices=[(1, 'Not specified'), (2, 'Borrow'), (3, 'Donate')], default=1, verbose_name='')),
            ],
        ),
    ]
