# Generated by Django 2.0 on 2018-01-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_artifactcontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifactcontact',
            name='intend_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Not specified'), (2, 'Borrow'), (3, 'Donate')], default=1, verbose_name='Intend type'),
        ),
    ]
