# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 22:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('acceptance_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Pending approval'), (2, 'Missing info'), (3, 'Approved'), (4, 'Rejected')], default=1, verbose_name='Status')),
                ('is_private', models.BooleanField(default=False, verbose_name='Privately owned artifact')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('year_era', models.CharField(max_length=200, verbose_name='Era/Years range')),
                ('technical_data', models.TextField(verbose_name='Technical data')),
                ('description', models.TextField(verbose_name='Description')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='Short description')),
                ('origin_city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('origin_country', django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Country')),
                ('origin_area', models.CharField(blank=True, max_length=250, null=True, verbose_name='Area')),
                ('is_displayed', models.BooleanField(default=False, verbose_name='Displayed in museum?')),
                ('displayed_at', models.CharField(blank=True, max_length=250, null=True, verbose_name='Artifact location in museum')),
                ('donor_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Donor name')),
                ('display_donor_name', models.BooleanField(default=False, verbose_name='Display donor name?')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_artifacts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArtifactImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='artifacts/', verbose_name='Image')),
                ('description', models.CharField(blank=True, max_length=400, null=True, verbose_name='Description')),
                ('credit', models.CharField(blank=True, max_length=200, null=True, verbose_name='Credit')),
                ('year_era', models.CharField(blank=True, max_length=200, null=True, verbose_name='Year/Era')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Image location')),
                ('is_cover', models.BooleanField(default=False, verbose_name='Cover image?')),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='artifacts.Artifact', verbose_name='Artifact')),
            ],
        ),
        migrations.CreateModel(
            name='ArtifactImageCoord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.CharField(max_length=10, verbose_name='X')),
                ('y', models.CharField(max_length=10, verbose_name='Y')),
                ('width', models.CharField(blank=True, max_length=10, null=True, verbose_name='Width')),
                ('height', models.CharField(blank=True, max_length=10, null=True, verbose_name='Height')),
                ('info', models.CharField(blank=True, max_length=400, null=True, verbose_name='Info')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coords', to='artifacts.ArtifactImage', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='artifacts.Category', verbose_name='Parent category')),
            ],
        ),
        migrations.AddField(
            model_name='artifact',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='artifacts.Category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_artifacts', to=settings.AUTH_USER_MODEL),
        ),
    ]
