# Generated by Django 2.0 on 2017-12-12 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0003_auto_20171211_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifact',
            name='short_description',
        ),
    ]
