# Generated by Django 2.0 on 2017-12-17 07:15

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0004_remove_artifact_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
