# Generated by Django 2.0 on 2017-12-17 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0005_auto_20171217_0715'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtifactMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='ArtifactType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
            ],
        ),
        migrations.AddField(
            model_name='artifact',
            name='artifact_materials',
            field=models.ManyToManyField(blank=True, related_name='artifacts', to='artifacts.ArtifactMaterial', verbose_name='Artifact material'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='artifact_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='artifacts.ArtifactType', verbose_name='Artifact type'),
        ),
    ]
