# Generated by Django 2.0 on 2017-12-22 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0006_auto_20171217_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifact',
            name='tags',
        ),
    ]
