# Generated by Django 2.0 on 2017-12-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0007_remove_artifact_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(blank=True, choices=[('museum_collections', 'Museum collections'), ('users_collections', 'Users collections'), ('all_collections', 'All collections'), ('about', 'About'), ('contact', 'Contact'), ('account', 'Account'), ('login', 'Login'), ('upload_step_1', 'Upload step 1'), ('upload_step_2', 'Upload step 2'), ('upload_step_3', 'Upload step 3')], max_length=250, null=True, verbose_name='Page')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Image')),
                ('main_text', models.CharField(blank=True, max_length=400, null=True, verbose_name='Main text')),
                ('description', models.CharField(blank=True, max_length=400, null=True, verbose_name='Description')),
                ('credit', models.CharField(blank=True, max_length=200, null=True, verbose_name='Credit')),
                ('active', models.BooleanField(default=True, verbose_name='Active?')),
            ],
        ),
    ]
