# Generated by Django 2.0 on 2017-12-22 09:57

import django.contrib.postgres.fields
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0008_pagebanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='OriginArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('countries', django.contrib.postgres.fields.ArrayField(base_field=django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='Country'), blank=True, null=True, size=None)),
            ],
        ),
        migrations.RemoveField(
            model_name='artifact',
            name='year_era',
        ),
        migrations.AddField(
            model_name='artifact',
            name='year_from',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Year from'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='year_to',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Year to'),
        ),
    ]
