# Generated by Django 2.0 on 2017-12-24 08:21

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0010_artifact_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originarea',
            name='countries',
            field=django_countries.fields.CountryField(blank=True, default='', max_length=746, multiple=True, verbose_name='Country'),
            preserve_default=False,
        ),
    ]
