# Generated by Django 2.0 on 2017-12-24 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0011_auto_20171224_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='origin_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='artifacts.OriginArea', verbose_name='Area'),
        ),
    ]
