# Generated by Django 2.0 on 2017-12-31 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0012_auto_20171224_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifact',
            name='description',
        ),
        migrations.RemoveField(
            model_name='artifact',
            name='donor_name',
        ),
        migrations.RemoveField(
            model_name='artifact',
            name='name',
        ),
        migrations.RemoveField(
            model_name='artifact',
            name='origin_city',
        ),
        migrations.RemoveField(
            model_name='artifact',
            name='technical_data',
        ),
        migrations.RemoveField(
            model_name='artifactimage',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='artifactmaterial',
            name='title',
        ),
        migrations.RemoveField(
            model_name='artifacttype',
            name='title',
        ),
        migrations.RemoveField(
            model_name='originarea',
            name='title',
        ),
        migrations.RemoveField(
            model_name='pagebanner',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='pagebanner',
            name='description',
        ),
        migrations.RemoveField(
            model_name='pagebanner',
            name='main_text',
        ),
        migrations.AddField(
            model_name='artifact',
            name='description_en',
            field=models.TextField(default='', verbose_name='Description english'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artifact',
            name='description_he',
            field=models.TextField(default='', verbose_name='Description hebrew'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artifact',
            name='donor_name_en',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Donor name english'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='donor_name_he',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Donor name hebrew'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='name_en',
            field=models.CharField(default='', max_length=250, verbose_name='Name english'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artifact',
            name='name_he',
            field=models.CharField(default='', max_length=250, verbose_name='Name hebrew'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artifact',
            name='origin_city_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City english'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='origin_city_he',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City hebrew'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='technical_data_en',
            field=models.TextField(default='', verbose_name='Technical data english'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artifact',
            name='technical_data_he',
            field=models.TextField(default='', verbose_name='Technical data hebrew'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artifactimage',
            name='credit_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Credit english'),
        ),
        migrations.AddField(
            model_name='artifactimage',
            name='credit_he',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Credit hebrew'),
        ),
        migrations.AddField(
            model_name='artifactmaterial',
            name='title_en',
            field=models.CharField(default='', max_length=250, verbose_name='Title english'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artifactmaterial',
            name='title_he',
            field=models.CharField(default='', max_length=250, verbose_name='Title hebrew'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artifacttype',
            name='title_en',
            field=models.CharField(default='', max_length=250, verbose_name='Title english'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artifacttype',
            name='title_he',
            field=models.CharField(default='', max_length=250, verbose_name='Title hebrew'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='originarea',
            name='title_en',
            field=models.CharField(default='', max_length=250, verbose_name='Title english'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='originarea',
            name='title_he',
            field=models.CharField(default='', max_length=250, verbose_name='Title hebrew'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagebanner',
            name='credit_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Credit english'),
        ),
        migrations.AddField(
            model_name='pagebanner',
            name='credit_he',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Credit hebrew'),
        ),
        migrations.AddField(
            model_name='pagebanner',
            name='description_en',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Description english'),
        ),
        migrations.AddField(
            model_name='pagebanner',
            name='description_he',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Description hebrew'),
        ),
        migrations.AddField(
            model_name='pagebanner',
            name='main_text_en',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Main text english'),
        ),
        migrations.AddField(
            model_name='pagebanner',
            name='main_text_he',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Main text hebrew'),
        ),
    ]
