# Generated by Django 2.0 on 2018-01-03 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0014_auto_20180103_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Featured'),
        ),
    ]
