# Generated by Django 2.0 on 2018-01-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0015_artifact_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='route_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Artifact route english'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='route_he',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Artifact route hebrew'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='route_map',
            field=models.ImageField(blank=True, null=True, upload_to='maps/', verbose_name='Artifact route map'),
        ),
    ]
