# Generated by Django 2.0 on 2018-01-07 08:21

import artifacts.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0016_auto_20180103_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description English'),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='description_he',
            field=models.TextField(blank=True, null=True, verbose_name='Description Hebrew'),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='donor_name_en',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Donor name English'),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='donor_name_he',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Donor name Hebrew'),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='name_en',
            field=models.CharField(max_length=250, verbose_name='Name English'),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='name_he',
            field=models.CharField(max_length=250, verbose_name='Name Hebrew'),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='origin_city_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City English'),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='origin_city_he',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City Hebrew'),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='route_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Artifact route English'),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='route_he',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Artifact route Hebrew'),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='route_map',
            field=models.ImageField(blank=True, null=True, upload_to=artifacts.utils.upload_func, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['bmp', 'bufr', 'cur', 'pcx', 'dcx', 'dds', 'ps', 'eps', 'fit', 'fits', 'fli', 'flc', 'fpx', 'ftc', 'ftu', 'gbr', 'gif', 'grib', 'h5', 'hdf', 'png', 'jp2', 'j2k', 'jpc', 'jpf', 'jpx', 'j2c', 'icns', 'ico', 'im', 'iim', 'tif', 'tiff', 'jfif', 'jpe', 'jpg', 'jpeg', 'mic', 'mpg', 'mpeg', 'mpo', 'msp', 'palm', 'pcd', 'pdf', 'pxr', 'pbm', 'pgm', 'ppm', 'psd', 'bw', 'rgb', 'rgba', 'sgi', 'ras', 'tga', 'webp', 'wmf', 'emf', 'xbm', 'xpm'])], verbose_name='Artifact route map'),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='technical_data_en',
            field=models.TextField(blank=True, null=True, verbose_name='Technical data English'),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='technical_data_he',
            field=models.TextField(blank=True, null=True, verbose_name='Technical data Hebrew'),
        ),
        migrations.AlterField(
            model_name='artifactimage',
            name='credit_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Credit English'),
        ),
        migrations.AlterField(
            model_name='artifactimage',
            name='credit_he',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Credit Hebrew'),
        ),
        migrations.AlterField(
            model_name='artifactimage',
            name='description_en',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Description English'),
        ),
        migrations.AlterField(
            model_name='artifactimage',
            name='description_he',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Description Hebrew'),
        ),
        migrations.AlterField(
            model_name='artifactimage',
            name='image',
            field=models.ImageField(upload_to=artifacts.utils.upload_func, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['bmp', 'bufr', 'cur', 'pcx', 'dcx', 'dds', 'ps', 'eps', 'fit', 'fits', 'fli', 'flc', 'fpx', 'ftc', 'ftu', 'gbr', 'gif', 'grib', 'h5', 'hdf', 'png', 'jp2', 'j2k', 'jpc', 'jpf', 'jpx', 'j2c', 'icns', 'ico', 'im', 'iim', 'tif', 'tiff', 'jfif', 'jpe', 'jpg', 'jpeg', 'mic', 'mpg', 'mpeg', 'mpo', 'msp', 'palm', 'pcd', 'pdf', 'pxr', 'pbm', 'pgm', 'ppm', 'psd', 'bw', 'rgb', 'rgba', 'sgi', 'ras', 'tga', 'webp', 'wmf', 'emf', 'xbm', 'xpm'])], verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='artifactimage',
            name='location_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Image location English'),
        ),
        migrations.AlterField(
            model_name='artifactimage',
            name='location_he',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Image location Hebrew'),
        ),
        migrations.AlterField(
            model_name='artifactimage',
            name='year_era_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Year/Era English'),
        ),
        migrations.AlterField(
            model_name='artifactimage',
            name='year_era_he',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Year/Era Hebrew'),
        ),
        migrations.AlterField(
            model_name='artifactmaterial',
            name='title_en',
            field=models.CharField(max_length=250, verbose_name='Title English'),
        ),
        migrations.AlterField(
            model_name='artifactmaterial',
            name='title_he',
            field=models.CharField(max_length=250, verbose_name='Title Hebrew'),
        ),
        migrations.AlterField(
            model_name='artifacttype',
            name='title_en',
            field=models.CharField(max_length=250, verbose_name='Title English'),
        ),
        migrations.AlterField(
            model_name='artifacttype',
            name='title_he',
            field=models.CharField(max_length=250, verbose_name='Title Hebrew'),
        ),
        migrations.AlterField(
            model_name='originarea',
            name='title_en',
            field=models.CharField(max_length=250, verbose_name='Title English'),
        ),
        migrations.AlterField(
            model_name='originarea',
            name='title_he',
            field=models.CharField(max_length=250, verbose_name='Title Hebrew'),
        ),
        migrations.AlterField(
            model_name='pagebanner',
            name='credit_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Credit English'),
        ),
        migrations.AlterField(
            model_name='pagebanner',
            name='credit_he',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Credit Hebrew'),
        ),
        migrations.AlterField(
            model_name='pagebanner',
            name='description_en',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Description English'),
        ),
        migrations.AlterField(
            model_name='pagebanner',
            name='description_he',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Description Hebrew'),
        ),
        migrations.AlterField(
            model_name='pagebanner',
            name='image',
            field=models.ImageField(upload_to=artifacts.utils.upload_func, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['bmp', 'bufr', 'cur', 'pcx', 'dcx', 'dds', 'ps', 'eps', 'fit', 'fits', 'fli', 'flc', 'fpx', 'ftc', 'ftu', 'gbr', 'gif', 'grib', 'h5', 'hdf', 'png', 'jp2', 'j2k', 'jpc', 'jpf', 'jpx', 'j2c', 'icns', 'ico', 'im', 'iim', 'tif', 'tiff', 'jfif', 'jpe', 'jpg', 'jpeg', 'mic', 'mpg', 'mpeg', 'mpo', 'msp', 'palm', 'pcd', 'pdf', 'pxr', 'pbm', 'pgm', 'ppm', 'psd', 'bw', 'rgb', 'rgba', 'sgi', 'ras', 'tga', 'webp', 'wmf', 'emf', 'xbm', 'xpm'])], verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='pagebanner',
            name='main_text_en',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Main text English'),
        ),
        migrations.AlterField(
            model_name='pagebanner',
            name='main_text_he',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Main text Hebrew'),
        ),
    ]
