# Generated by Django 2.0.2 on 2018-02-19 12:41

import artifacts.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0018_auto_20180111_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='originarea',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=artifacts.utils.upload_func, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['bmp', 'bufr', 'cur', 'pcx', 'dcx', 'dds', 'ps', 'eps', 'fit', 'fits', 'fli', 'flc', 'fpx', 'ftc', 'ftu', 'gbr', 'gif', 'grib', 'h5', 'hdf', 'png', 'jp2', 'j2k', 'jpc', 'jpf', 'jpx', 'j2c', 'icns', 'ico', 'im', 'iim', 'tif', 'tiff', 'jfif', 'jpe', 'jpg', 'jpeg', 'mic', 'mpg', 'mpeg', 'mpo', 'msp', 'palm', 'pcd', 'pdf', 'pxr', 'pbm', 'pgm', 'ppm', 'psd', 'bw', 'rgb', 'rgba', 'sgi', 'ras', 'tga', 'webp', 'wmf', 'emf', 'xbm', 'xpm'])], verbose_name='Background image'),
        ),
    ]
