# Generated by Django 2.0.2 on 2018-02-24 14:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0020_auto_20180221_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtifactImageCrop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_thumbnail', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Small thumbnail square')),
                ('small_thumbnail_vertical', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Small thumbnail vertical')),
                ('big_thumbnail', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Big thumbnail')),
                ('cover', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Cover')),
                ('footer', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Footer')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='artifacts.ArtifactImage', verbose_name='Image')),
            ],
        ),
    ]
