# Generated by Django 2.0.2 on 2018-02-24 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0021_artifactimagecrop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifactimagecrop',
            name='image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='artifacts.ArtifactImage', verbose_name='Image'),
        ),
    ]
