# Generated by Django 2.0.3 on 2018-03-12 18:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0022_auto_20180224_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifactimage',
            name='thumbnails',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Small thumbnail square'),
        ),
    ]
