# Generated by Django 2.0.3 on 2018-03-12 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0023_artifactimage_thumbnails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifactimagecrop',
            name='image',
        ),
        migrations.DeleteModel(
            name='ArtifactImageCrop',
        ),
    ]
