# Generated by Django 2.0.3 on 2018-03-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0024_auto_20180312_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='credit_en',
            field=models.CharField(blank=True, max_length=500, verbose_name='Artifact credit English'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='credit_he',
            field=models.CharField(blank=True, max_length=500, verbose_name='Artifact credit Hebrew'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='item_no',
            field=models.CharField(blank=True, max_length=250, verbose_name='Item No'),
        ),
    ]
